version: '3.8'
services:
  nginx:
    build: ./sd-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - math-server

  backend:
    build: ./sd-backend
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
      - math-server

  math-server:
    build: ./sd-math-server

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_DB: studsolver
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6

volumes:
  postgres-data:
